name: Continious Integration
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Change directory
        run: cd server
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
